name: Deploy to EKS

on:
  push:
    branches:
      - sfdsf

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials using OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
        role-session-name: github-actions
        aws-region: <AWS_REGION>

    # Step 3: Set up Docker and push the image to ECR (if not already pushed)
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t <ECR_REPO_URI>:latest .
        docker push <ECR_REPO_URI>:latest

    # Step 4: Update kubeconfig to interact with EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name <EKS_CLUSTER_NAME> --region <AWS_REGION>

    # Step 5: Deploy the app to EKS
    - name: Deploy to EKS
      run: kubectl apply -f k8s/deployment.yaml
